id: http://ralree.dyndns.org
title: Brutal Reader
author: Erik Gregg and the feedchamp originators
feeds:
  - http://feeds.feedburner.com/terralien-ships-log
  - http://feeds.feedburner.com/pelargir
  - http://feeds.feedburner.com/RyansScraps
  - http://feeds.feedburner.com/yfactorial
  - http://feeds.feedburner.com/liveandlearn
  - http://feeds.feedburner.com/WiseheartDesign
  - http://feeds.feedburner.com/codora
  - http://feeds.feedburner.com/TheGeekBlogOfCodora
  - http://tjstankus.com/feed/atom
  - http://feeds.feedburner.com/talbott-blog
  - http://feeds.feedburner.com/violasong
  - http://home.thewilliams.ws/feed
  - http://basement.thewilliams.ws/feed
  - http://fredmedlin.com/feed/
  - http://feeds.feedburner.com/StartTheInsanity
